-- Maritime Surveillance DB schema
-- PostgreSQL

DROP TABLE IF EXISTS vessel_positions CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS vessels CASCADE;

DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;

DROP TABLE IF EXISTS user_permissions CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT NULL,
  is_system SMALLINT NOT NULL DEFAULT 0,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE permissions (
  permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  module VARCHAR(50) NULL,
  description TEXT NULL,
  is_active SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role_id INTEGER NOT NULL REFERENCES roles(role_id),
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  profile_img VARCHAR(2048) NOT NULL DEFAULT 'https://res.cloudinary.com/dftbkrs4f/image/upload/v1732101562/avatar2_d0vokh.png',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_users_status CHECK (status IN ('pending', 'verified', 'disabled'))
);

CREATE TABLE role_permissions (
  role_id INTEGER NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  granted_by INTEGER NULL REFERENCES users(user_id) ON DELETE SET NULL,
  PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX idx_rp_permission ON role_permissions(permission_id);

CREATE TABLE user_roles (
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  assigned_by INTEGER NULL REFERENCES users(user_id) ON DELETE SET NULL,
  PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_ur_role ON user_roles(role_id);
CREATE INDEX idx_ur_assigned_by ON user_roles(assigned_by);

CREATE TABLE user_permissions (
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  assigned_by INTEGER NULL REFERENCES users(user_id) ON DELETE SET NULL,
  PRIMARY KEY (user_id, permission_id)
);
CREATE INDEX idx_up_permission ON user_permissions(permission_id);
CREATE INDEX idx_up_assigned_by ON user_permissions(assigned_by);

CREATE TABLE vessels (
  vessel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mmsi VARCHAR(9) NOT NULL UNIQUE,
  imo VARCHAR(10) NULL,
  name VARCHAR(120) NULL,
  callsign VARCHAR(20) NULL,
  flag VARCHAR(60) NULL,
  vessel_type VARCHAR(60) NULL,
  length_m NUMERIC(6,2) NULL,
  width_m NUMERIC(6,2) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_vessels_status CHECK (status IN ('active', 'inactive'))
);
CREATE INDEX idx_vessels_name ON vessels(name);

CREATE TABLE vessel_positions (
  position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vessel_id INTEGER NOT NULL REFERENCES vessels(vessel_id) ON DELETE CASCADE,
  recorded_at TIMESTAMPTZ NOT NULL,
  lat NUMERIC(9,6) NOT NULL,
  lon NUMERIC(9,6) NOT NULL,
  sog_kn NUMERIC(6,2) NULL,
  cog_deg NUMERIC(6,2) NULL,
  heading_deg SMALLINT NULL,
  nav_status VARCHAR(50) NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'ais',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_positions_source CHECK (source IN ('ais', 'radar', 'manual', 'fused'))
);
CREATE INDEX idx_positions_vessel_time ON vessel_positions(vessel_id, recorded_at);

CREATE TABLE alerts (
  alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vessel_id INTEGER NULL REFERENCES vessels(vessel_id) ON DELETE SET NULL,
  type VARCHAR(30) NOT NULL DEFAULT 'manual',
  severity VARCHAR(20) NOT NULL DEFAULT 'medium',
  status VARCHAR(20) NOT NULL DEFAULT 'open',
  title VARCHAR(255) NOT NULL,
  description TEXT NULL,
  created_by INTEGER NOT NULL REFERENCES users(user_id),
  assigned_to INTEGER NULL REFERENCES users(user_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ NULL DEFAULT NULL,
  CONSTRAINT chk_alerts_type CHECK (type IN ('geofence', 'speed', 'collision_risk', 'dark_vessel', 'manual')),
  CONSTRAINT chk_alerts_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CONSTRAINT chk_alerts_status CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed'))
);
CREATE INDEX idx_alerts_status ON alerts(status);
CREATE INDEX idx_alerts_severity ON alerts(severity);
CREATE INDEX idx_alerts_vessel ON alerts(vessel_id);

CREATE TABLE activities (
  activity_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  permission_id INTEGER NULL REFERENCES permissions(permission_id) ON DELETE SET NULL,
  method VARCHAR(10) NOT NULL,
  path VARCHAR(255) NOT NULL,
  status_code INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_activities_user ON activities(user_id);
CREATE INDEX idx_activities_permission ON activities(permission_id);
CREATE INDEX idx_activities_created_at ON activities(created_at);

CREATE TABLE notifications (
  notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  entity_type VARCHAR(50) NULL,
  entity_id INTEGER NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'medium',
  is_read SMALLINT NOT NULL DEFAULT 0,
  read_at TIMESTAMPTZ NULL DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_notifications_priority CHECK (priority IN ('low','medium','high','critical')),
  CONSTRAINT chk_notifications_is_read CHECK (is_read IN (0, 1))
);
CREATE INDEX idx_notifications_user ON notifications(user_id, is_read, created_at);
CREATE INDEX idx_notifications_type ON notifications(type);
CREATE INDEX idx_notifications_entity ON notifications(entity_type, entity_id);
